language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1

notifications:
  irc:
    use_notice: true
    skip_join: true
    channels: ["irc.freenode.org#imbo"]

branches:
  only:
    - develop
    - master

services:
  - memcached

before_install:
  - |
    # Install different version of APCu for different PHP-versions
    if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then
      APCU_VERSION=5
    else
      APCU_VERSION=4
    fi

    printf "\n" | pecl install apcu-$APCU_VERSION
  - printf "\n" | pecl install memcached
  - php -m

before_script:
  - echo 'apc.enable_cli=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-add .travis-php.ini
  - composer self-update
  - composer lint
  - composer install --prefer-dist

script:
  - ./vendor/bin/phpunit --verbose
