language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels: ["irc.freenode.org#imbo"]
branches:
  only:
    - develop
    - master
services:
  - memcached
before_install:
  - sudo add-apt-repository -y ppa:moti-p/cc
  - sudo apt-get update
  - sudo apt-get -y --reinstall install imagemagick
  - printf "\n" | pecl install apcu-4.0.10
  - printf "\n" | pecl install imagick
before_script:
  - phpenv config-add .travis-php.ini
  - composer self-update
  - composer -n --no-ansi install --prefer-source
script:
  - ./vendor/bin/phpunit --verbose
