language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1

notifications:
  irc:
    use_notice: true
    skip_join: true
    channels: ["irc.freenode.org#imbo"]

branches:
  only:
    - develop
    - master

services:
  - memcached

before_install:
  - |
    if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then
      printf "\n" | pecl install apcu
    else
      printf "\n" | pecl install -f apcu-4.0.11
    fi
  - printf "\n" | pecl install imagick
  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'apc.enable_cli=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - php -m

before_script:
  - composer self-update
  - composer lint
  - composer install --prefer-dist

script:
  - ./vendor/bin/phpunit --verbose
