language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0

notifications:
  irc:
    use_notice: true
    skip_join: true
    channels: ["irc.freenode.org#imbo"]

branches:
  only:
    - develop
    - master

services:
  - memcached

before_install:
  - printf "\n" | pecl install apcu
  - printf "\n" | pecl install memcached
  - php -m

before_script:
  - phpenv config-add .travis-php.ini
  - composer self-update
  - composer lint
  - composer install --prefer-dist

script:
  - ./vendor/bin/phpunit --verbose
